# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0853dd0f0610f6b27e18cf21591dba46c65161ed998b38ddf8b0f58e5b66f9b3fe2d0100a4e7b218a1f09a9c9bf7761608d85639030fe60a44821bd43b3e737

test:
  secret_key_base: 703cce05527e5ec70761dd3771eb53e2379912510b8ee5a3357faea87b74f1bd073e01ad1fd9645efbcd975e3f9d41c9bbd768749f99c3b77735480b646265ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
