# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58be89ccc4f0febd11f2a63716f19337bd4ff52d5565421f07a9cf276bdd61ce3e10fc30095ed96cac7cedafd35a1bff0c80c0d13dc54137c92ca6ec474b1a3c

test:
  secret_key_base: dba08f6c8f928dc67c74b7a08c9c5cc5cb3758fc0a0d53dccb0eca63e669086550c2cd1a4b5ccd4b63e08f9cdc4f28d5dcd2b2aa94d244c102052018b7881224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
